name: Pilgaard EddyCovariance Continuous Delivery

on:
  push:
    tags:
      - eddycovariance-v*.*.*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore NuGet packages
        run: dotnet restore ./src/Pilgaard.EddyCovariance/Pilgaard.EddyCovariance.csproj

      - name: Build
        run: dotnet build ./src/Pilgaard.EddyCovariance/Pilgaard.EddyCovariance.csproj -c Release --no-restore

      - name: Run Tests
        run: >
          dotnet test ./tests/Pilgaard.EddyCovariance.Tests/Pilgaard.EddyCovariance.Tests.csproj --no-build --no-restore
          --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true" 
          --filter Category!=SkipInCI

      - name: Package Nugets
        run: dotnet pack ./src/Pilgaard.EddyCovariance/Pilgaard.EddyCovariance.csproj -c Release --no-build --no-restore --include-source

      - name: Push Nugets
        run: dotnet nuget push "**/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
